Repository Yoavcwix/Wix-CLI-Example, pull requests merged in 2024-03, with the labels that each got.

#2 add new line for text5
  src/pages/Home.c1dmp.js
Labels: documentation, enhancement

#5 onHover added to text5
  .eslintrc.json
  .gitignore
  README.md
  package-lock.json
  package.json
  src/backend/README.md
  src/backend/permissions.json
  src/pages/Home.c1dmp.js
  src/pages/README.md
  src/pages/masterPage.js
  src/public/README.md
  wix.config.json
Labels: good first issue

#3 add onHover
  package-lock.json
  src/pages/Home.c1dmp.js
Labels: enhancement
